version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DATABASE: nest-quiz-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - 5432:5432